# Generated by Django 3.2.19 on 2025-07-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controler', '0002_withdrawrequest_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='T',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('wnum', models.CharField(max_length=20)),
            ],
        ),
    ]
